// front-end/react/components/Chat.tsx
import { useState, useRef, useEffect, useCallback } from 'react';
import { useChat } from '../hooks/useChat';
import JoinScreen from './JoinScreen';
import ConnectedUsers from './ConnectedUsers';
import MessageList from './MessageList';
import ChatInput from './ChatInput';

const WS_URL = 'wss://c3wj3ucjda.execute-api.us-east-1.amazonaws.com/production/';

/**
 * Chat — orchestration only. No markup, no JSX template logic.
 * All visual rendering is delegated to sub-components.
 *
 * Equivalent to chat.ts in Angular — the component class without the template.
 */
export default function Chat() {

  const { messages, connectedUsers, connectionState, connect, sendMessage } = useChat();

  const [inputValue, setInputValue] = useState('');
  const [displayName, setDisplayName] = useState('');
  const [connected, setConnected] = useState(false);

  // Equivalent to @ViewChild('messageContainer')
  const messageContainerRef = useRef<HTMLDivElement>(null);

  // Equivalent to ngAfterViewChecked → scrollToBottom
  useEffect(() => {
    try {
      if (messageContainerRef.current) {
        messageContainerRef.current.scrollTop = messageContainerRef.current.scrollHeight;
      }
    } catch (e) {}
  }, [messages]);

  const join = useCallback(() => {
    if (!displayName.trim()) return;
    connect(WS_URL, displayName.trim());
    setConnected(true);
  }, [displayName, connect]);

  const onNameKeydown = useCallback((event: React.KeyboardEvent) => {
    if (event.key === 'Enter') join();
  }, [join]);

  const send = useCallback(() => {
    if (!inputValue.trim()) return;
    sendMessage(inputValue.trim());
    setInputValue('');
  }, [inputValue, sendMessage]);

  const onKeydown = useCallback((event: React.KeyboardEvent) => {
    if (event.key === 'Enter') send();
  }, [send]);

  return (
    <div className="border border-gray-100 rounded-xl overflow-hidden">

      {/* Live header */}
      <div className="bg-gray-950 border-b border-gray-800 px-5 py-3 flex items-center gap-2">
        <div className="w-2 h-2 rounded-full bg-green-400 animate-ping" />
        <span className="text-xs text-gray-400 font-medium">
          Live · Open on two devices to see real-time updates
        </span>
      </div>

      <div className="flex flex-col h-[600px] bg-gray-950 rounded-b-xl overflow-hidden border border-gray-800">

        {!connected ? (
          <JoinScreen
            displayName={displayName}
            onDisplayNameChange={setDisplayName}
            onJoin={join}
            onKeydown={onNameKeydown}
          />
        ) : (
          <>
            {/* Mobile connected users strip */}
            <ConnectedUsers users={connectedUsers} />

            <div className="flex flex-1 overflow-hidden">

              {/* Message area */}
              <div className="flex-1 flex flex-col overflow-hidden">
                <MessageList
                  ref={messageContainerRef}
                  messages={messages}
                  displayName={displayName}
                />
                <ChatInput
                  inputValue={inputValue}
                  onInputChange={setInputValue}
                  onSend={send}
                  onKeydown={onKeydown}
                />
              </div>

              {/* Desktop sidebar — rendered inside ConnectedUsers */}
              <ConnectedUsers users={connectedUsers} />

            </div>
          </>
        )}

      </div>
    </div>
  );
}

// front-end/angular/chat/components/chat/chat.ts
import { Component, ElementRef, ViewChild } from '@angular/core';
import { ChatMessage, ChatService, ConnectedUser } from '../../services/chat-service';
import { Observable } from 'rxjs';

@Component({
  selector: 'app-chat',
  standalone: false,
  templateUrl: './chat.html',
})
export class Chat {
@ViewChild('messageContainer') messageContainer!: ElementRef;

  messages$: Observable<ChatMessage[]>;
  connectedUsers$: Observable<ConnectedUser[]>;
  inputValue = '';
  displayName = '';
  connected = false;

  constructor(private chatService: ChatService) {
    this.messages$ = this.chatService.messages$;
    this.connectedUsers$ = this.chatService.connectedUsers$;
  }

  ngOnInit(): void {}

  ngAfterViewChecked(): void {
    this.scrollToBottom();
  }

  scrollToBottom(): void {
    try {
      this.messageContainer.nativeElement.scrollTop =
        this.messageContainer.nativeElement.scrollHeight;
    } catch (e) {}
  }

  join(): void {
    if (!this.displayName.trim()) return;
    this.chatService.connect(
      'wss://c3wj3ucjda.execute-api.us-east-1.amazonaws.com/production/',
      this.displayName.trim()
    );
    this.connected = true;
  }

  onNameKeydown(event: KeyboardEvent): void {
    if (event.key === 'Enter') this.join();
  }

  send(): void {
    if (!this.inputValue.trim()) return;
    this.chatService.sendMessage(this.inputValue.trim());
    this.inputValue = '';
  }

  onKeydown(event: KeyboardEvent): void {
    if (event.key === 'Enter') this.send();
  }

  truncate(connectionId: string): string {
    return connectionId.substring(0, 8) + '...';
  }

  timeAgo(date: Date): string {
    const seconds = Math.floor((new Date().getTime() - new Date(date).getTime()) / 1000);
    if (seconds < 10) return 'just now';
    if (seconds < 60) return `${seconds}s ago`;
    const minutes = Math.floor(seconds / 60);
    if (minutes < 60) return `${minutes}m ago`;
    const hours = Math.floor(minutes / 60);
    if (hours < 24) return `${hours}h ago`;
    const days = Math.floor(hours / 24);
    return `${days}d ago`;
  }
}
